### ISSUE TITLE
Metatable support

### ISSUE THREAD

**Issue by Nemoos-0** [kepano/obsidian-minimal#139]
The metatable plugin generate a table, that substitute the original metadata frontmatter, in order to show all the metadata and not only tags and aliases, but it looks out of place.

Could it be possible to restyle it to make it look like the regular frontmatter?

Thanks.

**Comment by alanalvarado** [comment]
This is very easy, I already did it, use this snippet

```css
.obsidian-metatable {
	--metatable-font-family: var(--font-ui);
	--metatable-foreground: var(--text-normal);
	--metatable-key-background: var(--background-primary-alt);
	--metatable-key-border-color: var(--background-primary-alt);
	--metatable-value-background: var(--background-primary-alt);
}

.obsidian-metatable::part(link) {
	white-space: normal;
}


```
