### ISSUE TITLE
Better File explorer indentation

### ISSUE THREAD

**Issue by adamhl8** [kepano/obsidian-minimal#153]
The current way files are indented in the file explorer is a bit confusing/hard to look at in my opinion. Currently, files are aligned with their parent folder, almost making it look like they're not inside a folder at all.

I'm using a CSS snippet to adjust this, but it would be nice if this was part of the theme and if there was a setting to adjust it.

![before](https://user-images.githubusercontent.com/1844269/151081160-a9baa2a3-4eb7-44f2-afc3-f464b5f11227.png)

```css
/* By default, .nav-file has a margin-left of 12px. An additional 15px are needed to properly align them with adjacent folders. */
.nav-folder.mod-root .nav-folder .nav-file {
  margin-left: 27px;
}
```

![after](https://user-images.githubusercontent.com/1844269/151081215-28d01c8b-a005-4cf9-87ba-6acff69b8146.png)
