### ISSUE TITLE
Undesired Auto-stretch of images to Max Screen Width

### ISSUE THREAD

**Issue by mochsner** [kepano/obsidian-minimal#17]
This functionality should be overriden, somehow. It is possible

Desired (default) display of images in Obsidian => about 40% width of screen, 60% vertical height
![image](https://user-images.githubusercontent.com/19310711/127175965-0408555b-cb91-4e34-8de6-1840e966971f.png)

Display for Minimal theme (far too wide, and then image takes up 200% vertical height due to width stretch:
![image](https://user-images.githubusercontent.com/19310711/127176288-9971f44f-5dfb-439e-ac2c-b4a628a3afd0.png)

Potential Solutions:
1. Not stretching
2. Stretching only to 50% max (if stretched):
https://forum.obsidian.md/t/resize-embedded-content/877/13
3. Alt tag overloading for custom sizes (taken as the only working option for Obsidian from [this](https://www.xaprb.com/blog/how-to-style-images-with-markdown/) markdown article).

Note, I've gotten this (#3) desired functionality by disabling the Minimal theme (minimal overrides custom CSS), and using the following CSS Snippet:

```css
.markdown-preview-view img[alt="sm"] {
  max-width:30%;
  max-height:auto;
}
.markdown-preview-view img[alt="md"] {
  max-width:50%;
  max-height:auto;
}
.markdown-preview-view img[alt="lg"] {
  max-width:70%;
  max-height:auto;
}
```

This is activated using the following notation:
```markdown
![sm](Pasted%20image%2020210727084710.png)
![md](Pasted%20image%2020210727084710.png)
![lg](Pasted%20image%2020210727084710.png)
```

If this is something Obsidian minimal theme would like to support, I'd be very open to opening and submitting a pull request / support any breaking changes that Obsidian pushes (I'm an insider - https://forum.obsidian.md/u/mochsner/summary)

Thanks!
Marc
