### ISSUE TITLE
Show Vault name and Obsidian version in Title bar

### ISSUE THREAD

**Issue by dvdmtw98** [kepano/obsidian-minimal#221]
An option to show the name of the current vault and obsidian version on the title bar similar to the default Obsidian theme

**Comment by starise** [comment]
I'm on Linux and I'd like to have this option too.
Anyway it's an easy workaround using a CSS snippet like:
```css
.titlebar-text {
  display: block; !important
  color: rgb(15, 15, 15);
}
```
