### ISSUE TITLE
Subtasks in new Kanban Board plugin not showing checkmarks

### ISSUE THREAD

**Issue by jctan05** [kepano/obsidian-minimal#27]
When creating subtasks in the Kanban plugin, the subtasks checkmarks don't show up using Minimal Theme.

Results:

<img width="201" alt="Screen Shot 2021-09-16 at 6 08 58 PM" src="https://user-images.githubusercontent.com/38368029/133707776-422e57b7-b3b2-4fd9-9f59-8b864f5f08ea.png">

Expected:

<img width="209" alt="Screen Shot 2021-09-16 at 6 07 37 PM" src="https://user-images.githubusercontent.com/38368029/133707704-04e962e2-3322-4436-88b6-52c44f11d6b0.png">

Relevant markdown:

```
## Doing

- [ ] testcard<br><br>- [ ]  testsubtask<br>- [ ]  testsubtask2
```

**Comment by crashmoney** [comment]
This is an issue with the inline padding of the Minimal theme. The checkboxes are there, just pushed to the side and thus not visible. It can be fixed by adding the following CSS to the end of the Minimal theme (or any other themes that may be affected, e.g. Yin and Yang by Chetachi) or as a snippet (although this will influence other themes that may not be affected):

```css
/*temporary fix for Kanban plugin:
fixes padding so that checkboxes are visible*/
.kanban-plugin__markdown-preview-view ol.contains-task-list .contains-task-list,
.kanban-plugin__markdown-preview-view ul.contains-task-list .contains-task-list,
.kanban-plugin__markdown-preview-view ul, .kanban-plugin__markdown-preview-view
ol {
  padding-inline-start: 30px !important;
}
```
