### ISSUE TITLE
When rename long file name in "File Explorer", the full file name is not visible

### ISSUE THREAD

**Issue by yuru7** [kepano/obsidian-minimal#272]
Thank you for great work😊 I report the following.

# About the bug

When rename long file name in "File Explorer", the full file name is not visible.

![20220418_204020](https://user-images.githubusercontent.com/13458509/163803184-72a43fac-d1f1-4dd8-bb05-7c87a9fd151a.gif)

## Debug info

```
SYSTEM INFO:
	Obsidian version: v0.14.5
	Installer version: v0.14.2
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Safe mode: on

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
```

## Workaround

Apply the following CSS snippet.

```css
.nav-file-title-content {
  overflow: clip;
}

.is-being-renamed {
  overflow: hidden;
  text-overflow: clip;
}
```
