### ISSUE TITLE
lower part of hover effect not visible for buttons in modal dialogs

### ISSUE THREAD

**Issue by depressiveRobot** [kepano/obsidian-minimal#336]
Hello and thank you for making this really beautiful theme!

I found a little issue with buttons in modal dialogs. The lower part of the hover/active effect is not visible as you can see in the screenshot:

<img width="574" alt="Screen Shot 2022-06-10 at 11 02 48" src="https://user-images.githubusercontent.com/6043497/173031588-4b52b69c-1560-4db3-9a82-9dfddb897c0e.png">

I was able to fix it by changing the top and bottom margins for buttons in `.modal-button-container` class from

https://github.com/kepano/obsidian-minimal/blob/c253acee4eb91d6eb5c337fa2faa10338de90cc9/src/scss/obsidian/modals.scss#L40

to

```css
.modal-button-container button {
    margin-top: 5px;
    margin-bottom: 5px;
}
```
