### ISSUE TITLE
[Feature] Make the Todo task text darker if the checkbox is checked.

### ISSUE THREAD

**Issue by Teraskull** [kepano/obsidian-minimal#394]
**Describe the solution you'd like**
For example, this is how the "Things" theme shows todo text:
![image](https://user-images.githubusercontent.com/24798198/185420830-b1d80088-b522-43a5-8f47-cf22725c13bd.png)

**Comment by kepano** [comment]
I would recommend using a snippet for this

**Comment by Teraskull** [comment]
Snippet:
```css
.markdown-preview-view ul > li.task-list-item.is-checked {
    /* text-decoration: line-through !important; */
    color: var(--text-faint) !important;
}
```
