### ISSUE TITLE
Italics and/or bold parts of headings are not rendered correctly

### ISSUE THREAD

**Issue by idea-list** [kepano/obsidian-minimal#400]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

5.3.2

### Describe the bug

*This is not a critical issue for me, just a heads up since I know you work on a new default theme for Obsidian 0.16 (that's probably somewhat based on Minimal's codebase) so you can avoid it there.*

Minimal renders italics and/or bold text in headers differently and incorrectly in all modes due to clashes of CSS rules with different specificity. It can be reproduced in a brand new vault with only Minimal theme and a Minimal Theme Settings plugin installed.

#### Issues with Minimal theme only (these are reproducible no matter if Minimal Theme Settings is installed or not):
- *italic* and ***bold italic*** text is not italicized in `Source` and `Live Preview` modes.
- **bold** and ***bold italic*** text has same font weight as headings in `Source`, `Live Preview` and `Reading` modes
  I expect it to have a greater font weight even in H1 in case font supports such weights (e.g. if regular H1 weight = 600 → bold = 800).

#### Additional issue with Minimal Theme Settings' Colorful headings (but it seems to have a similar cause):
- Colorful headings' colors don't apply to *italic*, **bold** and ***bold italic*** parts of the headings.

#### Actual (Source, Live Preview, Reading modes):
<img width="602" alt="actual" src="https://user-images.githubusercontent.com/1430830/187935242-c3deb896-0c44-4834-8b75-02242db01fc7.png">

#### Expected (Source, Live Preview, Reading modes):
<img width="575" alt="expected" src="https://user-images.githubusercontent.com/1430830/187935360-44f0a73c-7685-4d3c-abba-dd9812947e7a.png">

#### Workaround

Currently I fixed this issue in my vault using the following CSS snippet. Sorry that this not a PR but:
1. I'm not sure it covers all cases. There seems to be more rules that apply font weights and/or colors.
2. I don't think this is the optimal solution as there might be a better way to apply such rules in a consistent way, because this is not an issue with current (Obsidian 0.15.9) default theme. I don't know if it's an issue in 0.16.x.

```css
/* Render italic parts in headings as italic */
.cm-em:is(.cm-header-1, .cm-header-2, .cm-header-3, .cm-header-4, .cm-header-5, .cm-header-6) {
  font-style: italic;
}

/* Increase font weight for bold parts of the headings */
.markdown-rendered h1 strong, .cm-s-obsidian .cm-header-1.cm-strong {
  font-weight: calc(var(--h1-weight) + var(--bold-weight) - var(--normal-weight));
}

.markdown-rendered h2 strong, .cm-s-obsidian .cm-header-2.cm-strong {
  font-weight: calc(var(--h2-weight) + var(--bold-weight) - var(--normal-weight));
}

.markdown-rendered h3 strong, .cm-s-obsidian .cm-header-3.cm-strong {
  font-weight: calc(var(--h3-weight) + var(--bold-weight) - var(--normal-weight));
}

.markdown-rendered h4 strong, .cm-s-obsidian .cm-header-4.cm-strong {
  font-weight: calc(var(--h4-weight) + var(--bold-weight) - var(--normal-weight));
}

.markdown-rendered h5 strong, .cm-s-obsidian .cm-header-5.cm-strong {
  font-weight: calc(var(--h5-weight) + var(--bold-weight) - var(--normal-weight));
}

.markdown-rendered h6 strong, .cm-s-obsidian .cm-header-6.cm-strong {
  font-weight: calc(var(--h6-weight) + var(--bold-weight) - var(--normal-weight));
}

/* Apply Colorful headings's colors to bold and italic parts of the headings */
.markdown-rendered h1 :where(strong, em) {
    color: var(--h1-color);
}

.markdown-rendered h2 :where(strong, em) {
    color: var(--h2-color);
}

.markdown-rendered h3 :where(strong, em) {
    color: var(--h3-color);
}

.markdown-rendered h4 :where(strong, em) {
    color: var(--h4-color);
}

.markdown-rendered h5 :where(strong, em) {
    color: var(--h5-color);
}

.markdown-rendered h6 :where(strong, em) {
    color: var(--h6-color);
}
```

### Debug info

```
SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Minimal Theme Settings v5.3.2
```
