### ISSUE TITLE
Inconsistent indentation with dataview embedded lists

### ISSUE THREAD

**Issue by zerowidth** [kepano/obsidian-minimal#410]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.0.4

### Describe the bug

The styles for dataview embedded lists are applied inconsistently in two ways:

* The rendered view (right pane) has an indent applied to the `taskList` that isn't present in the live preview (see `Grouped` section). I'd prefer the non-indented, "strict embed" style, but consistency between the two would be nice, and/or an easy way to override.
* The first-level list items (see `Ungrouped` section) are outdented when the `taskList` is rendered without grouping. The ungrouped version lacks a `div` with `dataview result-group` class wrapping the `ul`.

<img width="1038" alt="Screen Shot 2022-09-08 at 9 12 32 PM" src="https://user-images.githubusercontent.com/3999/189264452-15d93a4c-426e-45d8-8844-ea5124841b76.png">

Raw markdown:

~~~
## Tasks

- [ ] one
    - [ ] subtask
- [ ] two

## Dataview

### Grouped

```js
dv.taskList(dv.current().file.tasks, true)
```

```dataviewjs
dv.taskList(dv.current().file.tasks, true)
```

### Ungrouped

```js
dv.taskList(dv.current().file.tasks, false)
```

```dataviewjs
dv.taskList(dv.current().file.tasks, false)
```
~~~

### Debug info

```
SYSTEM INFO:
	Obsidian version: v0.16.2
	Installer version: v0.15.9
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 57
	Plugins enabled: 2
		1: Dataview v0.5.45
		2: Minimal Theme Settings v6.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

I notice this says I have 1 snippet enabled still, but the two custom `css` files I use are disabled in settings.

**Comment by zerowidth** [comment]
I was able to get alignment to be more consistent by resetting the `max-width:var(--max-width);` from `line-width.scss`. My override (using the generated selectors)

```css
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataview h4,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataview>h4,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs h4,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs>h1,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs>h2,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs>h3,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs>h4,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .block-language-dataviewjs>p,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .dataview.dataview-container>.contains-task-list,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .dataview.dataview-error,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .dataview.list-view-ul,
body:not(.table-100):not(.table-max):not(.table-wide) .markdown-preview-view.is-readable-line-width:not(.table-100):not(.table-max):not(.table-wide) .dataview.result-group {
  max-width: 100%;
}
```

**Comment by StevenGLee** [comment]
Same problem. Waiting to be fixed officially.

**Comment by Koderok** [comment]
I'm also stuck trying to debug this issue. Please update if anyone was able to find a workaround. I'm using Minimal theme.

**Comment by kepano** [comment]
Please try again with Minimal 7.0+

**Comment by paolo-santucci** [comment]
I still have this issue:

![image](https://github.com/kepano/obsidian-minimal/assets/17023798/c5b8210a-e6c2-4dd8-a36f-1c8675bae823)

![image](https://github.com/kepano/obsidian-minimal/assets/17023798/c34b48b1-a0f0-46fa-aaca-3581426f985f)

---

But it's also present while using the default theme:

![image](https://github.com/kepano/obsidian-minimal/assets/17023798/4edbfefe-d437-4638-97ce-431dd4c64076)

![image](https://github.com/kepano/obsidian-minimal/assets/17023798/2560a8b3-87bb-4c8c-b4bd-775dc1bfcc50)

**Comment by zerowidth** [comment]
Yeah, still looks like it's not quite consistent. Edit mode on the left, view mode on the right:

<img width="829" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/3999/495e8048-4b2d-4638-bb79-3408be3e7524">

**Comment by paolo-santucci** [comment]
This

```css
.is-live-preview ul[class="contains-task-list"]{
	padding-left: 1.9em !important;
	text-indent: -1.5em !important
}
```

Seems to solve the issue, on my device, for Dataview, but not for Tasks.

**Comment by paolo-santucci** [comment]
OK, this seems to solve the issue for me:

```css
/* fix for Dataview checklists */
.is-live-preview ul[class="contains-task-list"]{
	padding-left: 1.9em !important;
	text-indent: -1.5em !important
}

/* fix for Tasks checklists */
.is-live-preview ul > li.plugin-tasks-list-item {
	padding-left: 0em !important;
	text-indent: -1.5em !important
}
```
