### ISSUE TITLE
Make color of automatic weblinks configurable

### ISSUE THREAD

**Issue by eikowagenknecht** [kepano/obsidian-minimal#471]
**Is your feature request related to a problem? Please describe.**
Links like <https://minimal.is.great/> are shown in gray despite having a color for external links configured.

**Describe the solution you'd like**
I "fixed" it with
```css
.cm-s-obsidian span.cm-formatting-link.cm-url {
    color: var(--link-external-color);
}
```

Would be nice if the color for those links would either be the same as for other external links or cunfigurable by itself.
