### ISSUE TITLE
Export Cards to PDF?

### ISSUE THREAD

**Issue by ReaderGuy42** [kepano/obsidian-minimal#480]
**Is your feature request related to a problem? Please describe.**
So far when you export a Cards table to PDF it just shows up as a regular table, not one that's formatted as is seen on the screen via Cards.

**Describe the solution you'd like**
A way to export the Cards table to PDF, so it looks like what is seen there.

Thanks!

**Comment by sunsoy** [comment]
@kepano is it possible to have PDF export respect image filters?

currently the output PDF skips any images with filter tags

```css
.theme-dark {
	img[src$="#invert"],
	div[src$="#invert"] img,
	span[src$="#invert"] img {
		filter: invert(1) hue-rotate(180deg);
		mix-blend-mode: screen;
	}
	img[src$="#multiply"],
	div[src$="#multiply"] img,
	span[src$="#multiply"] img {
		mix-blend-mode: screen;
	}
}
```
