### ISSUE TITLE
Footnote references lose superscript style in live preview editing mode

### ISSUE THREAD

**Issue by hytor-yang** [kepano/obsidian-minimal#486]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### Describe the bug

footnote references are styled the same as body text, while they should be rendered as superscript. It is possibly caused by following style definition.

```css
.cm-s-obsidian span.cm-footref {
    font-size: var(--font-adaptive-normal);
}
/* the above overrides default style as below */
.cm-s-obsidian span.cm-footref, .cm-s-obsidian span.cm-blockid {
    font-size: var(--font-smallest);
}
```

### Debug info

SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 11
		1: Better Word Count v0.8.1
		2: Quick Switcher++ v2.2.1
		3: Remember cursor position v1.0.7
		4: Advanced Tables v0.17.3
		5: Add Codemirror matchbrackets.js v1.0.0
		6: Easy Typing v5.0.11
		7: Minimal Theme Settings v6.1.0
		8: Contextual Typography v2.2.4
		9: Hider v1.2.3
		10: Style Settings v0.4.12
		11: Better footnote v1.0.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
