### ISSUE TITLE
Support for Obsidian Zoom Plugin

### ISSUE THREAD

**Issue by niklasravnsborg** [kepano/obsidian-minimal#488]
https://github.com/vslinko/obsidian-zoom provides a way to focus on specific headings and subtitles. With the default theme it looks fine, but with Minimal it doesn't look right. I think that the styling is not optimal, since it's missing some padding on the left.

<img width="1390" alt="Screenshot 2022-11-10 at 13 57 32" src="https://user-images.githubusercontent.com/6717303/201112925-69d3836b-4076-4c2f-a1a6-84cf3f41ca66.png">

I added some padding in my `custom.css` with this snippet:

```css
.cm-panels.cm-panels-top {
  padding: 0 var(--size-4-3);
}
```
