### ISSUE TITLE
Fixes broken indentation line in editor (source mode)

### ISSUE THREAD

**Issue by edentsai** [kepano/obsidian-minimal#497]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### Describe the bug

Hi, I found some CSS snippet for fixes broken indentation line in Editor
(but I not sure it can fit all of scenario).

#### Ration

I found the problem is the components (blockqoutes, codeblock, list item and etc)
are used difference font type and font-size that cause it's rendered `span.cm-indent` 
may have difference width, so `span.cm-indent::before { border-right: 1px ... }` elements
cannot be aligned to draw a  properly indentation guide.

#### CSS Snippet

here is my CSS snippet for fix broken indentation line in editor for reference:

```css
/**
 * IMPORTANT:
 *
 * Find the max font-size which are used in editor,
 * then set all of span.cm-indent to use same max font-size and same font type
 * for render same width to draw border-right as indentation lines.
 */
.markdown-source-view.mod-cm6 .cm-indent {
  /** TODO: add the missing font-size variables if need */
  font-size: max(
    var(--blockquote-size, var(--font-adaptive-normal)),
    var(--code-size, var(--font-adaptive-normal)),
    var(--font-adaptive-normal, var(--editor-font-size))
  );

  /* Or just use a fixed font-size: */
  /* font-size: 16px */
  
  /** 
   * Note that difference font types will also render span.cm-indent with difference width.
   * 
   * Just set it to the same font type you like.
   */
  font-family: Menlo;
}

/**
 * For Blockquotes use same margin-left with .HyperMD-list-line.
 *
 * this `margin-left: ...` copied from the CSS selector: `.markdown-source-view.mod-cm6.is-readable-line-width .HyperMD-list-line`
 */
.markdown-source-view.mod-cm6.is-readable-line-width .cm-line.HyperMD-quote {
  margin-left: max(
    calc(50% + var(--list-edit-offset) + var(--folding-offset) - var(--line-width-adaptive) / 2),
    calc(50% + var(--list-edit-offset) + var(--folding-offset) - var(--max-width) / 2)
  ) !important
}

.markdown-source-view.mod-cm6.is-readable-line-width .cm-line.HyperMD-codeblock {
  /**
   * Note that I have no idea why text-indent 4px
   * can fix codeblock's indentation line.
   * 
   * TODO: maybe find a properly variable or calc() logic (?) 
   **/
  text-indent: 4px;
}
```

#### Markdown Sample

```markdown
# Obsidian Minimal

## Fixes broken indentation lines in editor

-   Task 1 on Level 1
    
    ```txt
    Task 1 Description in codeblock.
    ```
      
    > [!INFO] Blockqoute Lvel 1
    > 
    > Task 1 Description in blockquote.
      
    - [ ] Sub Task 1.1 on Level 2
          
          
        ```txt
        Sub Task 1 Description in codeblock.
        ```
          
        > [!INFO] Blockquote Level 2
        > 
        > Sub Task 1 Description in blockquote. 
```

#### Demo: in editor by source mode

##### Before

<img width="957" alt="image" src="https://user-images.githubusercontent.com/5071526/202867121-a2c8dafe-dd29-4c83-bd93-7ccd30c7bd9c.png">

##### After

<img width="957" alt="2022-11-20-030547-Obsidian@2x" src="https://user-images.githubusercontent.com/5071526/202867395-9e7b9513-92af-4fe7-98c7-19bcbf6a3fc3.png">

#### Demo: in editor by preview mode

the CSS snippet only improve a little bit...

##### Before

<img width="957" alt="2022-11-20-030058-Obsidian@2x" src="https://user-images.githubusercontent.com/5071526/202867191-fe709c02-3bd4-4513-89ff-bacc96abc31d.png">

##### After

<img width="957" alt="2022-11-20-030112-Obsidian@2x" src="https://user-images.githubusercontent.com/5071526/202867201-7b0b9699-b9ec-436c-b727-fd9a1961bb2c.png">

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.0.3
	Installer version: v1.0.3
	Operating system: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 21.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: on

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
```
