### ISSUE TITLE
Numbered list showing up as unordered list on mobile

### ISSUE THREAD

**Issue by saucypilot** [kepano/obsidian-minimal#500]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

6.1.9

### What the bug is:
For some users on mobile, ordered lists (i.e. `1.`,  `2.`,  `3.`) gets render as a unordered list (i.e. `•`). For my case, nothing even shows up and my list looks like paragraphs. I tried every solution from deleting the app, disabling community plugins & CSS snippets, updating everything, and etc. The only fix I saw was using one theme I found but I prefer using [minimal].(https://github.com/kepano/obsidian-minimal) instead.

You can find example of this at [Obsidian forums](https://forum.obsidian.md/t/bug-numbered-list-changes-to-unordered-list-in-reading-view/46612/11?u=saucypilot).
### Enviroment:

- IOS version 16.1, iPhone 13

- Obsidian mobile version 1.4.1 with API version 1.0.3

### My only solution:
I was looking at other themes and only the [Obsidianite](https://github.com/bennyxguo/Obsidian-Obsidianite) theme didn't have this issue. So I looked at the code for their ordered list and used it as a CSS snippet and I was able to fix this issue for now. The only issues is that it makes the numbered lists a different colors I couldn't figure out how to revert it to the default color.

```css
 ol {
  list-style: none !important;
  counter-reset: li !important;
}

ol > li {
  counter-increment: li;
}

ol > li:not(.task-list-item)::before,
ul ol > li:not(.task-list-item)::before,
ul ul ol > li:not(.task-list-item)::before,
ul ul ul ol > li:not(.task-list-item)::before {
  content: '.' counter(li);
  color: var(--text-a);
  font-weight: normal;
  display: inline-block;
  width: 1em;
  margin-left: -1.5em;
  margin-right: 0.5em;
  text-align: right;
  direction: rtl;
  overflow: visible;
  word-break: keep-all;
  white-space: nowrap;
}
```
