### ISSUE TITLE
[Suggestion] Allow disabling the sort option

### ISSUE THREAD

**Issue by abaracedo** [kepano/obsidian-minimal#552]
Can you consider adding an option like `sortable` (by default can be set to `true`) so, when the value is set to `false` the button for sorting the elements is not rendered?

I have some cards where sorting is not required as I only use them to make the items look better.

**Comment by kepano** [comment]
I would recommend doing this as a snippet that you can activate via cssClass

e.g.

```css
.cards.cards-nosort table.dataview thead {
  display:none;
}
```

and use `cards-nosort` in your CSS classes
