### ISSUE TITLE
Image radiu conflicts with Minimal cards

### ISSUE THREAD

**Issue by icebruce** [kepano/obsidian-minimal#635]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.2.1

### Describe the bug

Image radius settings affects the cover image when using Minimal cards. Ideally I think the radius setting should only apply to images when used in notes.

![image](https://github.com/kepano/obsidian-minimal/assets/66655064/9395d529-0cc5-402b-9f57-bfe1639fe88c)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.3
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.1
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 35

**Comment by jloh** [comment]
This CSS snippet fixes the issue:

```css
/* Remove radius for images in cards to fix curved corners */
.cards img:not(.emoji) {
	border-radius: unset;
}
```
