### ISSUE TITLE
Fix non-circular bullet points 

### ISSUE THREAD

**Issue by andrewgazelka** [kepano/obsidian-minimal#639]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.2.1

### Describe the bug

Bullet points are not always round, especially when small

![image](https://github.com/kepano/obsidian-minimal/assets/7644264/c186c476-b02c-40be-82de-411b1667223c)

Fix:

```css
.list-bullet {
  /* fix aliasing https://chat.openai.com/share/0e9943e4-60c0-4eed-b9b5-16a7a93a42ba */
  will-change: transform;
}

.list-bullet:after {
  /* fixes aliasing for sub-bullets */
  will-change: transform;
}


```

![image](https://github.com/kepano/obsidian-minimal/assets/7644264/22cce752-5466-49ce-a08b-69d28795aea4)

I did not provide a PR as I am not sure where this should be included.
