### ISSUE TITLE
In Obsidian 1.5.3 + Minimal Theme 7.4.3, there is a misalignment issue with the positioning of tables.

### ISSUE THREAD

**Issue by alexinea** [kepano/obsidian-minimal#679]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.4.3

### Describe the bug

I have submitted this issue under the Minimal Theme Settings project. I cannot be certain whether this is an issue with Minimal Theme or Minimal Theme Settings, so I have submitted it for both.

The detailed description of the issue is as follows:
https://github.com/kepano/obsidian-minimal-settings/issues/73

### Debug info

```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.26016
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 9
		1: Thino v2.1.4
		2: Admonition v10.1.1
		3: Advanced URI v1.38.1
		4: Dataview v0.5.64
		5: Hider v1.3.1
		6: Minimal Theme Settings v7.3.1
		7: Obsidian42 - BRAT v0.12
		8: Style Settings v1.0.7
		9: Sortable v0.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by unix2dos** [comment]
tables cannot be dragged and dropped

**Comment by alexinea** [comment]
Addition: The tables generated by DataView do not experience positional displacement.

**Comment by Sinled** [comment]
Also have this problem

**Comment by alexinea** [comment]
I found that this issue doesn't seem to be fixed in Minimal Theme version [7.4.5](https://github.com/kepano/obsidian-minimal/releases/tag/7.4.5). 

But still, thanks to @kepano for trying to work around this bug.

**Comment by Sinled** [comment]
Any chances for this to be fixed?

**Comment by kepano** [comment]
There have been some improvements in 7.4.5. For now I would recommend using a different setting in `Maximize table width` — a full fix will take more time.

**Comment by kepano** [comment]
@Sinled can you share a screenshot of the issue you are seeing. Make sure you are using Minimal 7.4.7+ and let me know which table settings you are using.

**Comment by Sinled** [comment]
@kepano  There is unnecessary margin on `table` element, 

<img width="1208" alt="Screenshot 2024-01-08 at 13 30 30" src="https://github.com/kepano/obsidian-minimal/assets/1402135/16999317-6f45-4421-b3c0-1c02a1172477">

At the same time there are similar margins on table containing element
<img width="1222" alt="Screenshot 2024-01-08 at 13 32 40" src="https://github.com/kepano/obsidian-minimal/assets/1402135/16e7c880-e00a-4159-bcc7-97b1d27b7ecd">

No additional table related classes for this note.
`Maximize table width` is set to `always fill`, and i am using latest (7.4.7) version of theme

Here are full settings related to tables
<img width="671" alt="Screenshot 2024-01-08 at 13 35 25" src="https://github.com/kepano/obsidian-minimal/assets/1402135/dde7ef1d-bd16-4966-8280-361073567e9a">

At the moment i fixed it with custom styles removing margin from table, but it seems, as mentioned before, removing `important` from `marging-inline` here

```css
.markdown-preview-view.is-readable-line-width .markdown-preview-sizer .cm-table-widget,
.markdown-preview-view.is-readable-line-width .markdown-preview-sizer>div:has(>table),
.markdown-source-view.mod-cm6.is-readable-line-width .cm-contentContainer.cm-contentContainer>.cm-content .cm-table-widget, 
.markdown-source-view.mod-cm6.is-readable-line-width .cm-contentContainer.cm-contentContainer>.cm-content>div:has(>table) {
    width: var(--container-table-width);
    max-width: var(--container-table-max-width);
    margin-inline: var(--container-table-margin)!important;
}
```

also fixes problem
