### ISSUE TITLE
Left Sidebar Icons not visible 

### ISSUE THREAD

**Issue by nico-lechatnoir** [kepano/obsidian-minimal#731]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.5

### Describe the bug

Currently when using the theme and the default enabled snippets that are found though style settings the left sidebar icons intersect with the MacOS. All sidebar tab styles intersect but it at various amounts. The screenshots use the default modern compact option.

When the sidebar is expanded:
<img width="242" alt="1" src="https://github.com/kepano/obsidian-minimal/assets/144506187/5729b75e-9b0c-4a19-a04c-a02a1f73a58c">
When the sidebar is collapsed:
<img width="117" alt="2" src="https://github.com/kepano/obsidian-minimal/assets/144506187/832a99dc-c552-4695-acbb-9979d1b24af7">

### Debug info

I used the inspector to adjust the padding so all icons are visible.
```css
.is-hidden-frameless:not(.is-fullscreen) .workspace-tabs.mod-top-left-space .workspace-tab-header-container { padding-left: 80px; }
```
