### ISSUE TITLE
More Catppuccin Flavors

### ISSUE THREAD

**Issue by DensityInfinite** [kepano/obsidian-minimal#739]
The Catppuccin color scheme was suggested in #323 and added in [6.1.0](https://github.com/kepano/obsidian-minimal/releases/tag/6.1.0). However, only one dark palette (seems to be Frappé) was implemented, not the darker macchiato and mocha variants.

**Describe the solution you'd like**
It will be nice if the [other two flavors](https://catppuccin.com/palette) are implemented as well.

*Lastly, Thank you for the awesome theme and your hard work! I always jump back and forth between themes, and every time I eventually settle back to Minimal. All the best!*

**Comment by dhruvinsh** [comment]
Here is my implementation for mocha color,

```css
.theme-dark.minimal-catppuccin-dark {
	--color-red-rgb: 243,139,168; /* Red */
	--color-orange-rgb: 250,179,135; /* Peach */
	--color-yellow-rgb: 249,226,175; /* Yellow */
	--color-green-rgb: 166,227,161; /* Green */
	--color-cyan-rgb: 148,226,213; /* Teal */
	--color-blue-rgb: 137,180,250; /* Blue */
	--color-purple-rgb: 203,166,247; /* Mauve */
	--color-pink-rgb: 245,194,231; /* Pink */

	--color-red: #f38ba8; /* Red */
	--color-orange: #fab387; /* Peach */
	--color-yellow: #f9e2af; /* Yellow */
	--color-green: #a6e3a1; /* Green */
	--color-cyan: #94e2d5; /* Teal */
	--color-blue: #89b4fa; /* Blue */
	--color-purple: #cba6f7; /* Mauve */
	--color-pink: #f5c2e7; /* Pink */
}

.theme-light.minimal-catppuccin-light.minimal-light-contrast .titlebar,
.theme-light.minimal-catppuccin-light.minimal-light-contrast.minimal-status-off .status-bar,
.theme-light.minimal-catppuccin-light.minimal-light-contrast .workspace-drawer.mod-left,
.theme-light.minimal-catppuccin-light.minimal-light-contrast .mod-left-split,
.theme-light.minimal-catppuccin-light.minimal-light-contrast .workspace-ribbon.mod-left:not(.is-collapsed),
.theme-light.minimal-catppuccin-light.minimal-light-contrast .theme-dark,
.theme-dark.minimal-catppuccin-dark {
	--base-h: 237; /* Surface0 */
	--base-s: 16%; /* Surface0 */
	--base-l: 23%; /* Surface0 */

	--accent-h: 10; /* Rosewater */
	--accent-s: 56%; /* Rosewater */
	--accent-l: 91%; /* Rosewater */

	--bg1: #1e1e2e; /* Base */
	--bg2: #181825; /* Mantle */
	--bg3: #313244; /* Surface0 */

	--ui1: #45475a; /* Surface1 */
	--ui2: #585b70; /* Surface2 */
	--ui3: #6c7086; /* Overlay0 */

	--tx1: #cdd6f4; /* Text */
	--tx2: #a6adc8; /* Subtext0 */
	--tx3: #9399b2; /* Overlay2 */

	--sp1: #242634; /* Mantle */

	--hl1: rgba(108, 112, 134, 0.5); /* Overlay0 */
	--hl2: rgba(250, 179, 135, 0.4); /* Peach */
}
```
