### ISSUE TITLE
Add option for customizing the active tab elements within a tab stack for better tracking

### ISSUE THREAD

**Issue by jtmusky** [kepano/obsidian-minimal#839]
**Is your feature request related to a problem? Please describe.**
Would like to see an option for modifying the color of the active tab (Text, or border, or something) within a tab stack to be more prominent.  Having multiple (8+) tabs open causes loss of visibility of which tab is open. 

**Describe the solution you'd like**
- preferred : Use the inherent theme colors to style the active tab within a tab stack to be more prominent.  Text, or more inverse the color scheme, or something that grabs the eye to mitigate losing track of the active tab.
- optional: Add options in either the minimal setting plugin, or customization within the "Style Settings" to allow enhanced customization.

A [helpful discord user provided this css snippet](https://discord.com/channels/686053708261228577/931008597557649410/1378555437137399910) that does mostly I'm asking, but would like for this theme to officially support the active tab stack tab user customization.

-- Thank you for considering

**CSS Snippet** 

```css
.workspace-tabs.mod-stacked .workspace-tab-header.mod-active {
    border: 1px solid rgba(255, 165, 0, 0.7);
}

.workspace-tabs.mod-stacked .workspace-tab-header.mod-active .workspace-tab-header-inner-title {
    color: salmon;
}
```
