### ISSUE TITLE
Support table width for bases in code blocks

### ISSUE THREAD

**Issue by Comprehensive-Jason** [kepano/obsidian-minimal#842]
**Is your feature request related to a problem? Please describe.**
Right now, bases in code blocks fit the regular note's narrowness, while Dataview tables are able to take up the entire page width via Minimal Theme.

**Describe the solution you'd like**
Make bases in code blocks the same width as Dataview tables. Something like this should suffice:

```css
.cm-lang-base {
    width: 88% !important; 
}
```
